# Generated by Django 4.1.3 on 2022-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
            ],
        ),
    ]
